---
title: "SankeyDiagramCode"
author: "Kyra Gmoser-Daskalakis"
date: "7/7/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r setup}
setwd("C:/Users/kyras/OneDrive/Desktop/SLRSurvey/SLRSurvey/CurrentFiles/Data")
AdjMatrix <- read.csv("AdjacencyMatrix_Sankey.csv")
RespGroups <- read.csv("RespGroups_Sankey.csv")

RespGroups$ResponseId <- RespGroups$respondentID

merged <- merge(AdjMatrix, RespGroups, by="ResponseId")


merged$Group <- ifelse(merged$P_G1>merged$P_G2 & merged$P_G1>merged$P_G3, 1, 
ifelse(merged$P_G2>merged$P_G1 & merged$P_G2>merged$P_G3, 2,3))

table(merged$Group)

str(merged)

Sankey <- merged[, c(2:43, 87)]
Sankey <- Sankey[, c(1:28, 43)]

colnames(Sankey) <- c("SLRPlan", "Vulnerable", "LocalTax", "Lobby", "Permits", "InfoPlatform", "DACs", "GreenInfra", "Vision", "InnovDesign", "LocalResponse", "RegionalAuthority", "ExistingAgency", "Collab", "OtherP", "Transpo", "Water", "Stormwater", "Energy", "Ecosystem", "Erosion", "Commercial", "DACsC", "EconGrowth", "PropertyValue", "Housing", "PublicHealth", "OtherC", "Group")

library(dplyr)
library(tidyverse)

Sankey %>% 
  group_by(Sankey$Group) %>% 
  count(SLR.Plan.x=="1")
#Group 1 is 111 Yes, 178 No and Group 2 is 29 Yes, 97 No, and Group 3 is 121 Yes, 162 No

Sankey %>% 
  group_by(Sankey$Group) %>% 
  count(Vulnerable.x=="1")

Sankey %>% 
  group_by(Sankey$Group) %>% 
  count(Local.Tax.x=="1")

Sankey %>% 
  group_by(Sankey$Group) %>% 
  count(Lobby.x=="1")

Sankey %>% 
  group_by(Sankey$Group) %>% 
  count(Permits.x=="1")

Sankey %>% 
  group_by(Sankey$Group) %>% 
  count(Info.Platform.x=="1")

Sankey %>% 
  group_by(Sankey$Group) %>% 
  count(DACs.x=="1")

Sankey %>% 
  group_by(Sankey$Group) %>% 
  count(Green.Infra.x=="1")

Sankey %>% 
  group_by(Sankey$Group) %>% 
  count(Vision.x=="1")

Sankey %>% 
  group_by(Sankey$Group) %>% 
  count(Innov.Design.x=="1")

Sankey %>% 
  group_by(Sankey$Group) %>% 
  count(Local.Response.x=="1")

Sankey %>% 
  group_by(Sankey$Group) %>% 
  count(Regional.Authority.x=="1")

Sankey %>% 
  group_by(Sankey$Group) %>% 
  count(Existing.Agency.x=="1")

Sankey %>% 
  group_by(Sankey$Group) %>% 
  count(Collab.x=="1")

Sankey %>% 
  group_by(Sankey$Group) %>% 
  count(OtherP=="1")

Sankey %>% 
  group_by(Sankey$Group) %>% 
  count(Transpo.x=="1")

Sankey %>% 
  group_by(Sankey$Group) %>% 
  count(Water.x=="1")

Sankey %>% 
  group_by(Sankey$Group) %>% 
  count(Stormwater.x=="1")

Sankey %>% 
  group_by(Sankey$Group) %>% 
  count(Energy.x=="1")

Sankey %>% 
  group_by(Sankey$Group) %>% 
  count(Ecosystem.x=="1")

Sankey %>% 
  group_by(Sankey$Group) %>% 
  count(Erosion.x=="1")

Sankey %>% 
  group_by(Sankey$Group) %>% 
  count(Commercial.x=="1")

Sankey %>% 
  group_by(Sankey$Group) %>% 
  count(DACsC.x=="1")

Sankey %>% 
  group_by(Sankey$Group) %>% 
  count(Econ.Growth.x=="1")

Sankey %>% 
  group_by(Sankey$Group) %>% 
  count(Property.Value.x=="1")

Sankey %>% 
  group_by(Sankey$Group) %>% 
  count(Housing.x=="1")

Sankey %>% 
  group_by(Sankey$Group) %>% 
  count(Public.Health.x=="1")

Sankey %>% 
  group_by(Sankey$Group) %>% 
  count(OtherC=="1")

#These are now in the Sankey_Counts.csv file in Current Files -> Data

```



```{r Sankey Diagram}
library(networkD3)

Sankey_counts <- read.csv("Sankey_Counts.csv")

SankeyCounts <- Sankey_counts[, 2:29]

colnames(SankeyCounts) <- c("SLRPlan", "Vulnerable", "LocalTax", "Lobby", "Permits", "InfoPlatform", "DACs", "GreenInfra", "Vision", "InnovDesign", "LocalResponse", "RegionalAuthority", "ExistingAgency", "Collab", "OtherP", "Transpo", "Water", "Stormwater", "Energy", "Ecosystem", "Erosion", "Commercial", "DACsC", "EconGrowth", "PropertyValue", "Housing", "PublicHealth", "OtherC")

links <- SankeyCounts %>% 
  as.data.frame() %>% 
  rownames_to_column(var="source") %>% 
  gather(key="target", value="value", -1) %>%
  filter(value != 0)

# From these flows we need to create a node data frame: it lists every entities involved in the flow
nodes <- data.frame(
  name=c(as.character(links$source), as.character(links$target)) %>% 
    unique()
  )
 
# With networkD3, connection must be provided using id, not using real name like in the links dataframe.. So we need to reformat it.
links$IDsource <- match(links$source, nodes$name)-1 
links$IDtarget <- match(links$target, nodes$name)-1
 
# Make the Network
sankey <- sankeyNetwork(Links = links, Nodes = nodes,
                     Source = "IDsource", Target = "IDtarget",
                     Value = "value", NodeID = "name", 
                     sinksRight=FALSE)

sankey



# prepare color scale: I give one specific color for each node type (group, policy, concern)
my_color <- 'd3.scaleOrdinal() .domain(["1", "2","3", "SLRPlan", "Vulnerable", "LocalTax","Lobby", "Permits", "InfoPlatform", "DACs", "GreenInfra", "Vision", "InnovDesign", "LocalResponse", "RegionalAuthority", "ExistingAgency", "Collab", "OtherP", "Transpo", "Water", "Stormwater", "Energy", "Ecosystem", "Erosion", "Commercial", "DACsC", "EconGrowth", "PropertyValue", "Housing", "PublicHealth", "OtherC"]) .range(["blue", "blue" , "blue", "green", "green", "green", "green", "green", "green", "green", "green", "green", "green", "green", "green", "green", "green", "green", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow"])'
 
# Make the Network. I call my colour scale with the colourScale argument
sankey_color <- sankeyNetwork(Links = links, Nodes = nodes, Source = "IDsource", Target = "IDtarget", 
              Value = "value", NodeID = "name", colourScale=my_color, iterations=0)
sankey_color

#exported as an html file and png
```

```{r Response Count Correlations}
#Looking for Significant Differences in Response Selection by Group
correlations_counts <- subset(RespGroups, select= c("P_G1", "P_G2", "P_G3", "SLR.Plan", "Vulnerable", "Local.Tax","Lobby", "Permits", "Info.Platform", "DACs", "Green.Infra", "Vision", "Innov.Design", "Local.Response", "Regional.Authority", "Existing.Agency", "Collab", "Transpo", "Water", "Stormwater", "Energy", "Ecosystem", "Erosion", "Commercial", "DACsC", "Econ.Growth", "Property.Value", "Housing", "Public.Health"))

correlations_counts[is.na(correlations_counts)]=0
correlationmatrix_counts <- cor(correlations_counts, method="kendall")
correlationmatrix_counts_sp <- cor(correlations_counts, method="spearman")

library("corrplot")
library("Hmisc")
#note that corrplot which I used for this only allows pearson and spearman- if we want kendall will need to do it another way
data.rcorr.pear <- rcorr(as.matrix(correlations_counts), type="pearson")
data.rcorr.sp <- rcorr(as.matrix(correlations_counts), type="spearman")

data.coeff.sp <- data.rcorr.sp$r
data.p.sp <- data.rcorr.sp$P
data.p.sp

significantp <- data.p.sp[,1:3]
threecolumncorr <- data.coeff.sp[,1:3]

significantp <- as.data.frame(significantp)
threecolumncorr <- as.data.frame(threecolumncorr)

significantp$PG1_p <- significantp$P_G1
significantp$PG2_p <- significantp$P_G2
significantp$PG3_p <- significantp$P_G3

threecolumncorr$PG1_r <- threecolumncorr$P_G1
threecolumncorr$PG2_r <- threecolumncorr$P_G2
threecolumncorr$PG3_r <- threecolumncorr$P_G3


significantp <- significantp[,4:6]
threecolumncorr <- threecolumncorr[,4:6]

threecolumncorr$names <- rownames(threecolumncorr)

corrmatrix <- as.data.frame(threecolumncorr$names)
corrmatrix$PG1_r <- threecolumncorr$PG1_r
corrmatrix$PG1_p <- significantp$PG1_p
corrmatrix$PG2_r <- threecolumncorr$PG2_r
corrmatrix$PG2_p <- significantp$PG2_p
corrmatrix$PG3_r <- threecolumncorr$PG3_r
corrmatrix$PG3_p <- significantp$PG3_p

?subset()
corrmatrix.sigG1 <- subset(corrmatrix, corrmatrix$PG1_p<0.05)
corrmatrix.sigG2 <- subset(corrmatrix, corrmatrix$PG2_p<0.05)
corrmatrix.sigG3 <- subset(corrmatrix, corrmatrix$PG3_p <0.05)

#Double check with pearson

data.coeff.p <- data.rcorr.pear$r
data.p.p <- data.rcorr.pear$P
data.p.p

significantp.pear <- data.p.p[,1:3]
threecolumncorr.pear <- data.coeff.p[,1:3]

significantp.pear <- as.data.frame(significantp.pear)
threecolumncorr.pear <- as.data.frame(threecolumncorr.pear)

significantp.pear$PG1_p <- significantp.pear$P_G1
significantp.pear$PG2_p <- significantp.pear$P_G2
significantp.pear$PG3_p <- significantp.pear$P_G3

threecolumncorr.pear$PG1_r <- threecolumncorr.pear$P_G1
threecolumncorr.pear$PG2_r <- threecolumncorr.pear$P_G2
threecolumncorr.pear$PG3_r <- threecolumncorr.pear$P_G3


significantp.pear <- significantp.pear[,4:6]
threecolumncorr.pear <- threecolumncorr.pear[,4:6]

threecolumncorr.pear$names <- rownames(threecolumncorr.pear)

corrmatrixp <- as.data.frame(threecolumncorr.pear$names)
corrmatrixp$PG1_r <- threecolumncorr.pear$PG1_r
corrmatrixp$PG1_p <- significantp.pear$PG1_p
corrmatrixp$PG2_r <- threecolumncorr.pear$PG2_r
corrmatrixp$PG2_p <- significantp.pear$PG2_p
corrmatrixp$PG3_r <- threecolumncorr.pear$PG3_r
corrmatrixp$PG3_p <- significantp.pear$PG3_p

?subset()
corrmatrix.sigG1.p <- subset(corrmatrixp, corrmatrixp$PG1_p<0.05)
corrmatrix.sigG2.p <- subset(corrmatrixp, corrmatrixp$PG2_p<0.05)
corrmatrix.sigG3.p <- subset(corrmatrixp, corrmatrixp$PG3_p <0.05)

```