setwd("C:/Users/kyras/OneDrive/Desktop/SLRSurvey/SLRSurvey/CurrentData")
library(igraph)
library(netrankr)

Top3Policies_Edgelist <- read.csv("Top3Policies_Edgelist.csv")
Top3Policies_Edgelist <- as.matrix(Top3Policies_Edgelist)
Top3PoliciesNetwork <- as.data.frame(rbind(Top3Policies_Edgelist [,1:2], Top3Policies_Edgelist[,2:3]))
g= graph.data.frame(Top3PoliciesNetwork)
plot(g, vertex.size=25, vertex.label.cex=.5, edge.curved=.1, edge.arrow.size=.3, edge.width=.7)
kamadalayout<-layout.kamada.kawai(g)
plot(g, layout=kamadalayout, vertex.size=20, vertex.label.cex=.5, edge.curve=.05, edge.arrow.size=.3, edge.width=.7)
fruchtermanlayout <- layout.fruchterman.reingold(g)
plot(g, layout=fruchtermanlayout, vertex.size=20, vertex.label.cex=.5, edge.curve=.05, edge.arrow.size=.3, edge.width=.7)
